GLOBAL:
  use_gpu: true
  resume: false
  device: '0,1' # 'cpu' or '0' or '0,1,2,3' ...
  epoch_num: 300
  save_result_dir: ./exp
  experiment_name: animal
  save_epoch_step: 1
  eval_epoch_step: 1
  pretrained_model: ./pretrained_model/resnet34.pth
  checkpoints: #exp/animal_backup/2022-09-26_10-09/checkpoints/best.pth
  use_visualdl: false
  distributed: true
  early_stop_patience: 10

TRAIN:
  dataset:
    data_dir: ./data_dir/
    transforms:
      Resize: 224
      RandomCrop: 224
      RandomHorizontalFlip: true
      RandomVerticalFlip: true
      ColorJitter:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 4

VAL:
  dataset:
    data_dir: ./data_dir/
    transforms:
      Resize: 224
      Normalize:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 4

MODEL:
  name: resnet34

CRITERION:
  name: CE
  COORD_RATIO: 1
  CLASSIFIER_RATIO: 0.5

OPTIMIZER:
  name: SGD
  weight_decay: 0.0005
  momentum: 0.9
  nesterov: true
  lr:
    name: cosine_lr
    lrf: 0.2
    learning_rate: 0.0015
    warmup_epoch: 5
